<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-2OII0J81" failures="1" tests="7" name="regression testing" time="0.072" errors="0" timestamp="2023-10-09T10:00:55 IST">
  <testcase classname="testngPractise.TestngPractise" name="test2" time="0.011">
    <failure type="java.lang.AssertionError" message="unable to execute the test">
      <![CDATA[java.lang.AssertionError: unable to execute the test
at testngPractise.TestngPractise.test2(TestngPractise.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="testngPractise.TestngPractise" name="test1" time="0.001"/>
  <testcase classname="testngPractise.TestngPractise" name="test3" time="0.001"/>
  <testcase classname="testngPractise.TestngPractise" name="test4" time="0.002"/>
  <testcase classname="testngPractise.TestngPractise" name="test5" time="0.002"/>
  <testcase classname="testngPractise.TestngPractise" name="test6" time="0.008"/>
  <testcase classname="testngPractise.TestngPractise" name="test7" time="0.003"/>
</testsuite> <!-- regression testing -->
