<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-2OII0J81" failures="1" tests="7" name="testngPractise.TestngPractise" time="0.028" errors="0" timestamp="2023-10-09T10:00:55 IST" skipped="0">
  <testcase classname="testngPractise.TestngPractise" name="test1" time="0.001"/>
  <system-out/>
  <testcase classname="testngPractise.TestngPractise" name="test2" time="0.011">
    <failure message="unable to execute the test" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: unable to execute the test
at org.testng.Assert.fail(Assert.java:99)
at testngPractise.TestngPractise.test2(TestngPractise.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
    </failure>
  </testcase> <!-- test2 -->
  <system-out/>
  <testcase classname="testngPractise.TestngPractise" name="test3" time="0.001"/>
  <system-out/>
  <testcase classname="testngPractise.TestngPractise" name="test4" time="0.002"/>
  <system-out/>
  <testcase classname="testngPractise.TestngPractise" name="test5" time="0.002"/>
  <system-out/>
  <testcase classname="testngPractise.TestngPractise" name="test6" time="0.008"/>
  <system-out/>
  <testcase classname="testngPractise.TestngPractise" name="test7" time="0.003"/>
  <system-out/>
</testsuite> <!-- testngPractise.TestngPractise -->
